spring:
  application:
    name: taskhub-api

springdoc:
  paths-to-match: /api/**

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never
